### ISSUE TITLE
Could not find phantomjs at the specified path

### ISSUE THREAD

**Issue by didibus** [raghur/mermaid-filter#11]
Trying to use mermaid-filter from linux openSuse Tumbleweed using pandoc version 1.19.2.1 and node v6.9.5 and npm 3.10.10. I'm getting the following error:

```
You had errors in your syntax. Use --help for further information.
Could not find phantomjs at the specified path.
fs.js:809
  return binding.rename(pathModule._makeLong(oldPath),
                 ^

Error: ENOENT: no such file or directory, rename 'inline/tmp-21291MMU47r258Sll.tmp.png' -> 'inline/diagram-2.png'
    at Error (native)
    at Object.fs.renameSync (fs.js:809:18)
    at mermaid (/usr/local/lib/node_modules/mermaid-filter/index.js:50:12)
    at /usr/local/lib/node_modules/mermaid-filter/node_modules/pandoc-filter/index.js:52:19
    at Array.forEach (native)
    at walk (/usr/local/lib/node_modules/mermaid-filter/node_modules/pandoc-filter/index.js:50:7)
    at /usr/local/lib/node_modules/mermaid-filter/node_modules/pandoc-filter/index.js:74:16
    at Array.forEach (native)
    at walk (/usr/local/lib/node_modules/mermaid-filter/node_modules/pandoc-filter/index.js:73:20)
    at filter (/usr/local/lib/node_modules/mermaid-filter/node_modules/pandoc-filter/index.js:36:10)
```

The only suspicious thing I saw was a warning about phantomjs being old, and that I should use phantomjs-prebuilt package instead which appeared when I installed mermaid-filter from npm.

Any idea why?

Thanks

**Comment by didibus** [comment]
I found the issue.

Inside index.js you need to change this line:

```
var cmd = __dirname + "/node_modules/.bin/mermaid -v -e " + __dirname + "/node_modules/.bin/phantomjs.cmd";
```

to this:

```
var cmd = __dirname + "/node_modules/.bin/mermaid -v -e " + __dirname + "/node_modules/.bin/phantomjs";
```

Because on linux, phantomjs.cmd does not exist, only phantomjs without the `.cmd` extension.

I'm not sure how this could be handled within the code, maybe detecting the running OS and setting the path based on it?

**Comment by raghur** [comment]
I don't think I should need the .cmd extension... I just merged in a PR - perhaps you could test that?
