### ISSUE TITLE
After fresh install, it does not work

### ISSUE THREAD

**Issue by jdvor** [raghur/mermaid-filter#120]
Fresh install on:
host: Ubuntu 22.04 LTS, x64
node version: v20.11.1
npm version: 10.2.4

1. `npm install --global mermaid-filter`
2. `pandoc test.md -o test.pdf --filter=mermaid-filter`

where test.md contains the same mermaid sample like README.md of this repository.

Immediately crashes PDF generation process with **error**:

```
node:child_process:965
    throw err;
    ^

Error: Command failed: "/usr/lib/node_modules/mermaid-filter/node_modules/.bin/mmdc"    -w 800 -s 1 -f -i "/tmp/tmp-48717my6rswN10hfs.tmp" -t default -b white -o "/tmp/tmp-48717my6rswN10hfs.tmp.png"

Error: Could not find Chromium (rev. 1108766). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /home/jan/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (file:///usr/lib/node_modules/mermaid-filter/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:263:27)
    at ChromeLauncher.executablePath (file:///usr/lib/node_modules/mermaid-filter/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:176:25)
    at ChromeLauncher.computeLaunchArguments (file:///usr/lib/node_modules/mermaid-filter/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:93:37)
    at async ChromeLauncher.launch (file:///usr/lib/node_modules/mermaid-filter/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:57:28)
    at async run (file:///usr/lib/node_modules/mermaid-filter/node_modules/@mermaid-js/mermaid-cli/src/index.js:404:19)
    at async cli (file:///usr/lib/node_modules/mermaid-filter/node_modules/@mermaid-js/mermaid-cli/src/index.js:184:3)


    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at mermaid (/usr/lib/node_modules/mermaid-filter/index.js:84:5)
    at /usr/lib/node_modules/mermaid-filter/index.js:164:12
    at /usr/lib/node_modules/mermaid-filter/node_modules/pandoc-filter/index.js:52:19
    at Array.forEach (<anonymous>)
    at walk (/usr/lib/node_modules/mermaid-filter/node_modules/pandoc-filter/index.js:50:7)
    at /usr/lib/node_modules/mermaid-filter/node_modules/pandoc-filter/index.js:74:16
    at Array.forEach (<anonymous>) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(1234) [Uint8Array] [
       10,  69, 114, 114, 111, 114,  58,  32,  67, 111, 117, 108,
      100,  32, 110, 111, 116,  32, 102, 105, 110, 100,  32,  67,
      104, 114, 111, 109, 105, 117, 109,  32,  40, 114, 101, 118,
       46,  32,  49,  49,  48,  56,  55,  54,  54,  41,  46,  32,
       84, 104, 105, 115,  32,  99,  97, 110,  32, 111,  99,  99,
      117, 114,  32, 105, 102,  32, 101, 105, 116, 104, 101, 114,
       10,  32,  49,  46,  32, 121, 111, 117,  32, 100, 105, 100,
       32, 110, 111, 116,  32, 112, 101, 114, 102, 111, 114, 109,
       32,  97, 110,  32,
      ... 1134 more items
    ]
  ],
  pid: 48729,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(1234) [Uint8Array] [
     10,  69, 114, 114, 111, 114,  58,  32,  67, 111, 117, 108,
    100,  32, 110, 111, 116,  32, 102, 105, 110, 100,  32,  67,
    104, 114, 111, 109, 105, 117, 109,  32,  40, 114, 101, 118,
     46,  32,  49,  49,  48,  56,  55,  54,  54,  41,  46,  32,
     84, 104, 105, 115,  32,  99,  97, 110,  32, 111,  99,  99,
    117, 114,  32, 105, 102,  32, 101, 105, 116, 104, 101, 114,
     10,  32,  49,  46,  32, 121, 111, 117,  32, 100, 105, 100,
     32, 110, 111, 116,  32, 112, 101, 114, 102, 111, 114, 109,
     32,  97, 110,  32,
    ... 1134 more items
  ]
}

Node.js v20.11.1
Error running filter mermaid-filter:
Filter returned error status 1
```

**Comment by kurokirasama** [comment]
I have the same issue in one of my machines. Strangely in one of them (both are the exact same) it works without problems

**Comment by jdvor** [comment]
I'm not a Node developer, but I've briefly checked docs for `puppeteer` package and it is supposed to install `chrome-headless-shell` binary and "Chrome for Testing" (later one is supposed to be into `$HOME/.cache/puppeteer`).
`mermaid-filter` does have `puppeteer` as dependency but even though the installation displayed no errors, it's puppeteer dependency does not seem to be installed correctly or fully. 
Perhaps there are missing installation procedure instructions, because I can see I have `puppeteer` installed in path, but there are no browsers installed in `$HOME/.cache/puppeteer`, so clearly the automatic installation of the browser (as described in https://pptr.dev/) did not happened.

**Comment by jdvor** [comment]
After a bit of fiddling with npm, I've realized the issue was on my side (again because I'm not a Node developer.
The full installation steps on Ubuntu and likely other Linux distros should be:

1. (if you never run npm before) `npm config set prefix '~/.local/'` (pointing the future installations to `$HOME/.local/bin`, which is expected on Linux and likely in your user PATH).
2. `npm install --global mermaid-filter`
3. `pandoc test.md -o test.pdf --filter=mermaid-filter`

If you skip 1., the global installation will not succeed, because it will try to create puppeteer cache in `$HOME/root`, which you do not have permissions for.
And if you assume you need `sudo npm install --global mermaid-filter` like I did, it will lead to successful installation but the browser will be installed for root and **not you**.
