### ISSUE TITLE
Bump `mermaid-cli` to 11

### ISSUE THREAD

**Issue by arbipher** [raghur/mermaid-filter#136]
`mermaid-cli` at `10.9.1` conflicts with recent Mac arm architecture. The error is here. The `Error: spawn Unknown system error -86` is said to be an architecture problem.

```shell
$ /opt/homebrew/lib/node_modules/mermaid-filter/node_modules/.bin/mmdc -w 800 -s 1 -f -i "/var/folders/s1/4f0tf3s97cn_dkx2ckzl69wc0000gn/T/tmp-7007Z5FBDkgo5qz8.tmp" -t default -b white -o "/var/folders/s1/4f0tf3s97cn_dkx2ckzl69wc0000gn/T/tmp-7007Z5FBDkgo5qz8.tmp.png"

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:753:9)
    at new Process (file:///opt/homebrew/lib/node_modules/mermaid-filter/node_modules/@puppeteer/browsers/lib/esm/launch.js:134:76)
    at launch (file:///opt/homebrew/lib/node_modules/mermaid-filter/node_modules/@puppeteer/browsers/lib/esm/launch.js:72:12)
    at ChromeLauncher.launch (file:///opt/homebrew/lib/node_modules/mermaid-filter/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:64:32)
    at async run (file:///opt/homebrew/lib/node_modules/mermaid-filter/node_modules/@mermaid-js/mermaid-cli/src/index.js:416:19)
    at async cli (file:///opt/homebrew/lib/node_modules/mermaid-filter/node_modules/@mermaid-js/mermaid-cli/src/index.js:192:3)
```

I can run the same command by replacing a recent `mermaid-cli`

```shell
$ mmdc -w 800 -s 1 -f -i "/var/folders/s1/4f0tf3s97cn_dkx2ckzl69wc0000gn/T/tmp-7007Z5FBDkgo5qz8.tmp" -t default -b white -o "/var/folders/s1/4f0tf3s97cn_dkx2ckzl69wc0000gn/T/tmp-7007Z5FBDkgo5qz8.tmp.png"
Generating single mermaid chart

$ mmdc --version
11.4.0
```

**Comment by autra** [comment]
It has been done on master 🥳 

Now we just need a release with that v11.

**Comment by autra** [comment]
Hi @raghur can we get a release please? I'm interesting in this fix https://github.com/mermaid-js/mermaid/pull/4436 in mermaid-cli v11. Thanks a lot! And thanks for this tool :-)

**Comment by nijotz** [comment]
It seems like mermaid-cli is at 11.12.0 now
