### ISSUE TITLE
Windows 10 file not found error

### ISSUE THREAD

**Issue by databinding-thierryiseli** [raghur/mermaid-filter#44]
Hi. I wanted to use the filter with pandoc on a Windows 10, but got this error:
```
Error: ENOENT: no such file or directory, open 'C:\Users\Mr\AppData\Local\Temp\tmp-1392pd059WckYir6.tmp.png'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at mermaid (C:\Users\Mr\AppData\Roaming\npm\node_modules\mermaid-filter\index.js:83:27)
    at C:\Users\Mr\AppData\Roaming\npm\node_modules\mermaid-filter\index.js:143:12
    at C:\Users\Mr\AppData\Roaming\npm\node_modules\mermaid-filter\node_modules\pandoc-filter\index.js:52:19
    at Array.forEach (<anonymous>)
    at walk (C:\Users\Mr\AppData\Roaming\npm\node_modules\mermaid-filter\node_modules\pandoc-filter\index.js:50:7)
    at C:\Users\Mr\AppData\Roaming\npm\node_modules\mermaid-filter\node_modules\pandoc-filter\index.js:74:16
    at Array.forEach (<anonymous>)
    at walk (C:\Users\Mr\AppData\Roaming\npm\node_modules\mermaid-filter\node_modules\pandoc-filter\index.js:73:20) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\Mr\\AppData\\Local\\Temp\\tmp-1392pd059WckYir6.tmp.png'
}
```
The command looks like this:
```
pandoc test.md --pdf-engine=wkhtmltopdf --metadata title="test" -o test.pdf -F mermaid-filter.cmd
```

**Comment by databinding-thierryiseli** [comment]
It's more like a wkhtmltopdf problem. With pdflatex it works.
