### ISSUE TITLE
SyntaxError: Unexpected token >

### ISSUE THREAD

**Issue by iagomosqueira** [raghur/mermaid-filter#5]
Followed installation instructions, and when calling

pandoc -F mermaid-filter -o WORKPLAN.pdf WORKPLAN.md

on a plain md file with

```{.mermaid width=100 format=png }
gantt
    title TASK - PROJECT, JAN-JUN 2016

    section Section
    Task1           :a1, 2014-01-01, 30d
    Task2           :after a1  , 20d
    section Another
    Task in sec     :2014-01-12  , 12d
    anther task     : 24d
```

I get

```
pandoc -F mermaid-filter -o WORKPLAN.pdf WORKPLAN.md

/usr/local/lib/node_modules/mermaid-filter/index.js:23
    attrs[2].map(item => {
                       ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
pandoc: Error running filter mermaid-filter
Filter returned error status 8
```

I am using pandoc 1.15.0.6 on Ubuntu 14.04. Any idea what the problem can be?

**Comment by raghur** [comment]
I believe API changed in 1.16 - see #2

**Comment by iagomosqueira** [comment]
I am now on pandoc 1.17.0.2, and after reinstalling I am afraid I still get an error on the same line

```
$ pandoc -t html -F mermaid-filter -o test.html test.md

/usr/local/lib/node_modules/mermaid-filter/index.js:23
    attrs[2].map(item => {
                       ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
pandoc: Error running filter mermaid-filter
Filter returned error status 8
```

**Comment by raghur** [comment]
Ok - that looks like you don't have a recent enough version of node that supports ES6 arrow functions? 

I created your file -
```
This is a markdown!
=====================

And a mermaid diagram

\```mermaid

gantt
    title TASK - PROJECT, JAN-JUN 2016

    section Section
    Task1           :a1, 2014-01-01, 30d
    Task2           :after a1  , 20d
    section Another
    Task in sec     :2014-01-12  , 12d
    anther task     : 24d

\```
```
and ran `pandoc -F mermaid-filter.cmd -o test.html test.md` and I got an html as below

```
<h1 id="this-is-a-markdown">This is a markdown!</h1>
<p>And a mermaid diagram</p>
<p><img src="img\diagram-2.png" /></p>
<p> </p>
```

My node version - 

```
D:\code\mermaid>node -v
v4.4.4
```

**Comment by iagomosqueira** [comment]
Thanks, it works after updating node via npm. Ubuntu 14.04 has a very 
old version.
