### ISSUE TITLE
breaks on macos 

### ISSUE THREAD

**Issue by felixhelix** [raghur/mermaid-filter#56]
Hi, 
I tried to convert your test.md to PDF using
`pandoc test.md --pdf-engine=xelatex -o test.pdf --filter=mermaid-filter`
Got the error below.
Using pandoc 2.2.3.2, but it also broke with older version (1.19 something).
It seems like the pandoc used is installed via anaconda: Maybe this can be a problem?
Any ideas?
Your's
Felix

```
internal/util.js:206
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:206:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/mermaid-filter/node_modules/extract-zip/index.js:11:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/mermaid-filter/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:48:39)

    at checkExecSyncError (child_process.js:591:13)
    at execSync (child_process.js:631:13)
    at mermaid (/usr/local/lib/node_modules/mermaid-filter/index.js:76:5)
    at /usr/local/lib/node_modules/mermaid-filter/index.js:143:12
    at /usr/local/lib/node_modules/mermaid-filter/node_modules/pandoc-filter/index.js:52:19
    at Array.forEach (<anonymous>)
    at walk (/usr/local/lib/node_modules/mermaid-filter/node_modules/pandoc-filter/index.js:50:7)
    at /usr/local/lib/node_modules/mermaid-filter/node_modules/pandoc-filter/index.js:74:16
    at Array.forEach (<anonymous>)
    at walk (/usr/local/lib/node_modules/mermaid-filter/node_modules/pandoc-filter/index.js:73:20)'
```

**Comment by raghur** [comment]
@felixhelix - I don't know.. I've not seen this before. Looks like something to do with puppeteer which is called by mermaid..
Seems like it's fetching a zip and extracting it? (just from the stack trace)

I don't have a mac so I'm not sure how to help. Can you try on a linux VM and just convert to HTML and see if that works?

**Comment by felixhelix** [comment]
Thanks rahgur: I searched for the error and pupeteer: 
found https://github.com/puppeteer/puppeteer/issues/5687 and noticed that my node version was far too old.
your's
Felix
