### ISSUE TITLE
Path to .mermaid.css is unquoted

### ISSUE THREAD

**Issue by profiluefter** [raghur/mermaid-filter#61]
I get the following error if I try to use this filter in a path that contains spaces. It probably occurs because the path to the .mermaid.css file is unqoted in some process call.

```
Error: Command failed: "C:\Users\User\AppData\Roaming\npm\node_modules\mermaid-filter\node_modules\.bin\mmdc"   -C C:\Users\User\Path\with spaces\.mermaid.css  -w 800 -f -i C:\Users\User\AppData\Local\Temp\tmp-8644XHAnI8v4XjvC.tmp -t default -o C:\Users\User\AppData\Local\Temp\tmp-8644XHAnI8v4XjvC.tmp.png
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at mermaid (C:\Users\User\AppData\Roaming\npm\node_modules\mermaid-filter\index.js:81:5)
    at C:\Users\User\AppData\Roaming\npm\node_modules\mermaid-filter\index.js:145:12
    at C:\Users\User\AppData\Roaming\npm\node_modules\mermaid-filter\node_modules\pandoc-filter\index.js:52:19
    at Array.forEach (<anonymous>)
    at walk (C:\Users\User\AppData\Roaming\npm\node_modules\mermaid-filter\node_modules\pandoc-filter\index.js:50:7)
    at C:\Users\User\AppData\Roaming\npm\node_modules\mermaid-filter\node_modules\pandoc-filter\index.js:74:16
    at Array.forEach (<anonymous>)
    at walk (C:\Users\User\AppData\Roaming\npm\node_modules\mermaid-filter\node_modules\pandoc-filter\index.js:73:20)
```

**Comment by davebaol** [comment]
Yes, there are a few places where quotes are missing:
- https://github.com/raghur/mermaid-filter/blob/5fb1156ad142e29d727d67288777f48876509bb7/index.js#L39
  it should be
  ```javascript
    confFileOpts += ` -c "${configFile}"`
  ```
- https://github.com/raghur/mermaid-filter/blob/5fb1156ad142e29d727d67288777f48876509bb7/index.js#L44
  it should be
  ```javascript
    puppeteerOpts += ` -p "${puppeteerConfig}"`
  ```
- https://github.com/raghur/mermaid-filter/blob/5fb1156ad142e29d727d67288777f48876509bb7/index.js#L48
  it should be
  ```javascript
    confFileOpts += ` -C "${cssFile}"`
  ```
- https://github.com/raghur/mermaid-filter/blob/5fb1156ad142e29d727d67288777f48876509bb7/index.js#L79
  it should be
  ```javascript
    var fullCmd = `"${cmd}"  ${confFileOpts} ${puppeteerOpts} -w ${options.width} -f -i "${tmpfileObj.name}" -t ${options.theme} -o "${savePath}"`
  ```

@raghur 
It would be great if you could fix them and publish a new version on npm 🥰
