### ISSUE TITLE
Non-obvious failure when dependencies not installed

### ISSUE THREAD

**Issue by r0b5t4** [raghur/mermaid-filter#74]
When external dependencies "mmdc" and "imgur" are not installed, pandoc conversion fails with the message below.

A check and more descriptive message would be helpful for those not into reading the source.

Thanks!

```
internal/fs/utils.js:269
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/tmp/tmp-4050GyYEzVHw52Af.tmp.png'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at mermaid (/home/user/.npm-global/lib/node_modules/mermaid-filter/index.js:88:27)
    at /home/user/.npm-global/lib/node_modules/mermaid-filter/index.js:145:12
    at /home/user/.npm-global/lib/node_modules/mermaid-filter/node_modules/pandoc-filter/index.js:52:19
    at Array.forEach (<anonymous>)
    at walk (/home/user/.npm-global/lib/node_modules/mermaid-filter/node_modules/pandoc-filter/index.js:50:7)
    at /home/user/.npm-global/lib/node_modules/mermaid-filter/node_modules/pandoc-filter/index.js:74:16
    at Array.forEach (<anonymous>)
    at walk (/home/user/.npm-global/lib/node_modules/mermaid-filter/node_modules/pandoc-filter/index.js:73:20) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/tmp/tmp-4050GyYEzVHw52Af.tmp.png'
}
Error running filter mermaid-filter:
Filter returned error status 1
```

**Comment by raghur** [comment]
This is on mmdc/mermaid project - we do try to do this - see `externalTool`
