### ISSUE TITLE
Cant use mermaid filter with pandoc

### ISSUE THREAD

**Issue by JustAlternate** [raghur/mermaid-filter#80]
Hello, I keep having this issue where I can't use the mermaid filter using pandoc

\`\`\`mermaid
graph LR
    A --> B
\`\`\`

when I do :

`$ pandoc test.md -o test.pdf -F mermaid-filter`

I keep having this error, no matter how many times i reinstalled npm or mermaid filter (im new to pandoc and javascript so this error might seem obvious for you, sorry about that)

error : 

```
/usr/local/lib/node_modules/mermaid-filter/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
[0404/163927.631210:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/usr/local/lib/node_modules/mermaid-filter/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at Interface.<anonymous> (/usr/local/lib/node_modules/mermaid-filter/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)
    at Interface.emit (node:events:538:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by schaveyt** [comment]
I found my issue. I was running this from Windows 10 WSL Linux. It did not have chome installed which is what this error ulitmatley complains about.

my fix was as follows:

~~~sh
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ./google-chrome-stable_current_amd64.deb
sudo npm install --location=global puppeteer || exit 1
sudo npm install --location=global mermaid-filter || exit 1
~~~

**Comment by acheong08** [comment]
I have Google Chrome installed but still get the same issue following the same steps
